// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv_aCqqv5HJq4170hWsZXYCEDnn6Rj_R4',
    appId: '1:523609687312:web:b0b72571250a22f3d09195',
    messagingSenderId: '523609687312',
    projectId: 'batchapp-4147a',
    authDomain: 'batchapp-4147a.firebaseapp.com',
    storageBucket: 'batchapp-4147a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlbYpvSO_Am0BLwfPrNqDuIwt7ZXSWRew',
    appId: '1:523609687312:android:812c79aa4c88d0dfd09195',
    messagingSenderId: '523609687312',
    projectId: 'batchapp-4147a',
    storageBucket: 'batchapp-4147a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaHJ2DfeT37AaM86sxSzE0kP_iHOM3PYA',
    appId: '1:523609687312:ios:427eae5c64e5dacfd09195',
    messagingSenderId: '523609687312',
    projectId: 'batchapp-4147a',
    storageBucket: 'batchapp-4147a.firebasestorage.app',
    iosBundleId: 'com.example.logiologyMachinetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaHJ2DfeT37AaM86sxSzE0kP_iHOM3PYA',
    appId: '1:523609687312:ios:427eae5c64e5dacfd09195',
    messagingSenderId: '523609687312',
    projectId: 'batchapp-4147a',
    storageBucket: 'batchapp-4147a.firebasestorage.app',
    iosBundleId: 'com.example.logiologyMachinetest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv_aCqqv5HJq4170hWsZXYCEDnn6Rj_R4',
    appId: '1:523609687312:web:cb5e69872c7588e2d09195',
    messagingSenderId: '523609687312',
    projectId: 'batchapp-4147a',
    authDomain: 'batchapp-4147a.firebaseapp.com',
    storageBucket: 'batchapp-4147a.firebasestorage.app',
  );
}
